// packages/react/src/dialog/drawer.tsx
"use client";

import { useId, type ReactNode } from "react";
import * as dialog from "@zag-js/dialog";
import { useMachine, normalizeProps, Portal } from "@zag-js/react";
import { type Side, type Size } from "@crosskit-ui/core";
import { usePresence } from "../use-presence";
import { Button } from "../button/button";

export interface DrawerProps {
  open?: boolean;
  defaultOpen?: boolean;
  onOpenChange?: (details: { open: boolean }) => void;
  /** v0 called this `position`. */
  placement?: Side;
  size?: Size;
  role?: "dialog" | "alertdialog";
  modal?: boolean;
  closeOnEscape?: boolean;
  closeOnInteractOutside?: boolean;
  showCloseButton?: boolean;
  id?: string;
  className?: string;
  title?: ReactNode;
  description?: ReactNode;
  footer?: ReactNode;
  children?: ReactNode;
}

/**
 * The same @zag-js/dialog machine as Modal. Only `data-ck="drawer"`,
 * `data-placement` and the animation differ — the focus trap, scroll lock,
 * Escape handling and ARIA wiring are all shared, which is the whole point of
 * putting behaviour in a machine.
 */
export function Drawer({
  placement = "right",
  size = "md",
  showCloseButton = true,
  id,
  className,
  title,
  description,
  footer,
  children,
  ...machineProps
}: DrawerProps) {
  const autoId = useId();
  const service = useMachine(dialog.machine, { id: id ?? autoId, ...machineProps });
  const api = dialog.connect(service, normalizeProps);
  const { present, setNode } = usePresence(api.open);

  if (!present) return null;

  return (
    <Portal>
      <div {...api.getBackdropProps()} data-ck="drawer" />
      <div {...api.getPositionerProps()} data-ck="drawer">
        <div
          ref={setNode}
          {...api.getContentProps()}
          data-ck="drawer"
          data-placement={placement}
          data-size={size}
          className={className}
        >
          {title != null && <h2 {...api.getTitleProps()}>{title}</h2>}
          {description != null && <p {...api.getDescriptionProps()}>{description}</p>}
          <div data-scope="dialog" data-part="body" data-ck="drawer">
            {children}
          </div>
          {footer != null && (
            <div data-scope="dialog" data-part="footer" data-ck="drawer">
              {footer}
            </div>
          )}
          {showCloseButton && (
            <Button
              variant="ghost"
              size="sm"
              icon="close"
              data-close-trigger=""
              aria-label="Close"
              onClick={() => api.setOpen(false)}
            />
          )}
        </div>
      </div>
    </Portal>
  );
}

// packages/vue/src/dialog/Drawer.vue
<script setup lang="ts">
import { computed, useId } from "vue";
import * as dialog from "@zag-js/dialog";
import { useMachine, normalizeProps } from "@zag-js/vue";
import type { Side, Size } from "@crosskit-ui/core";
import { usePresence } from "./usePresence";
import Button from "../button/Button.vue";

defineOptions({ inheritAttrs: false });

const props = withDefaults(
  defineProps<{
    open?: boolean;
    defaultOpen?: boolean;
    placement?: Side;
    size?: Size;
    role?: "dialog" | "alertdialog";
    modal?: boolean;
    closeOnEscape?: boolean;
    closeOnInteractOutside?: boolean;
    showCloseButton?: boolean;
    title?: string;
    description?: string;
    id?: string;
  }>(),
  { placement: "right", size: "md", showCloseButton: true }
);

const emit = defineEmits<{ "update:open": [boolean]; openChange: [{ open: boolean }] }>();

const autoId = useId();

const machineProps = computed(() => ({
  id: props.id ?? autoId,
  open: props.open,
  defaultOpen: props.defaultOpen,
  role: props.role,
  modal: props.modal,
  closeOnEscape: props.closeOnEscape,
  closeOnInteractOutside: props.closeOnInteractOutside,
  onOpenChange(details: { open: boolean }) {
    emit("update:open", details.open);
    emit("openChange", details);
  },
}));
const service = useMachine(dialog.machine, machineProps);

const api = computed(() => dialog.connect(service, normalizeProps));
const presence = usePresence(() => api.value.open);
</script>

<template>
  <Teleport to="body">
    <template v-if="presence.present.value">
      <div v-bind="api.getBackdropProps()" data-ck="drawer" />
      <div v-bind="api.getPositionerProps()" data-ck="drawer">
        <div
          :ref="el => presence.setNode(el as HTMLElement | null)"
          v-bind="{ ...api.getContentProps(), ...$attrs }"
          data-ck="drawer"
          :data-placement="props.placement"
          :data-size="props.size"
        >
          <h2 v-if="props.title || $slots.title" v-bind="api.getTitleProps()">
            <slot name="title">{{ props.title }}</slot>
          </h2>
          <p v-if="props.description || $slots.description" v-bind="api.getDescriptionProps()">
            <slot name="description">{{ props.description }}</slot>
          </p>
          <div data-scope="dialog" data-part="body" data-ck="drawer"><slot /></div>
          <div v-if="$slots.footer" data-scope="dialog" data-part="footer" data-ck="drawer">
            <slot name="footer" />
          </div>
          <Button
            v-if="props.showCloseButton"
            variant="ghost"
            size="sm"
            icon="close"
            data-close-trigger=""
            aria-label="Close"
            @click="api.setOpen(false)"
          />
        </div>
      </div>
    </template>
  </Teleport>
</template>
