// packages/svelte/src/tooltip/Tooltip.svelte
<script lang="ts">
  import type { Snippet } from "svelte";
  import * as tooltip from "@zag-js/tooltip";
  import { useMachine, normalizeProps, portal } from "@zag-js/svelte";
  import {
    isFocusVisible,
    resolvePlacement,
    type LegacyPlacement,
    type Placement,
  } from "@crosskit-ui/core";
  import { usePresence, presenceNode } from "../presence.svelte";

  interface Props {
    content?: string | Snippet;
    /** Accepts Floating UI names and v0's Ant names (`topLeft`, `rightBottom`, …). */
    placement?: Placement | LegacyPlacement;
    open?: boolean;
    defaultOpen?: boolean;
    onOpenChange?: (details: { open: boolean }) => void;
    openDelay?: number;
    closeDelay?: number;
    disabled?: boolean;
    class?: string;
    contentClass?: string;
    id?: string;
    children?: Snippet;
  }

  let {
    content,
    placement,
    open = $bindable(undefined),
    defaultOpen,
    onOpenChange,
    openDelay,
    closeDelay,
    disabled,
    class: klass,
    contentClass,
    id,
    children,
  }: Props = $props();

  const uid = $props.id();

  const service = useMachine(tooltip.machine, () => ({
    id: id ?? uid,
    open,
    defaultOpen,
    openDelay,
    closeDelay,
    disabled,
    positioning: { placement: resolvePlacement(placement) },
    onOpenChange(details: { open: boolean }) {
      open = details.open;
      onOpenChange?.(details);
    },
  }));

  const api = $derived(tooltip.connect(service, normalizeProps));
  const presence = usePresence(() => ({ present: api.open }));

  // zag types the trigger through normalize.button; this one lands on a <span>,
  // so the props are widened rather than the element being changed.
  const triggerProps = $derived(api.getTriggerProps() as Record<string, unknown>);
</script>

<!-- focus/blur do not bubble to a wrapper, so focusin/focusout stand in. React's
     synthetic events fake the bubbling and would have hidden this divergence. -->
<span
  {...triggerProps}
  class={klass}
  onfocusin={e => {
    if (isFocusVisible(e.target)) api.setOpen(true);
  }}
  onfocusout={() => api.setOpen(false)}
>
  {@render children?.()}
</span>

<!-- Gate on presence, NEVER on api.open, or [data-state="closed"] never gets a
     frame and the exit animation silently does nothing. -->
{#if presence.present}
  <div use:portal {...api.getPositionerProps()}>
    <div {...api.getContentProps()} class={contentClass} use:presenceNode={presence.setNode}>
      {#if typeof content === "string"}{content}{:else}{@render content?.()}{/if}
    </div>
  </div>
{/if}

// packages/vue/src/tooltip/Tooltip.vue
<script setup lang="ts">
import { computed, useId } from "vue";
import * as tooltip from "@zag-js/tooltip";
import { useMachine, normalizeProps } from "@zag-js/vue";
import {
  isFocusVisible,
  resolvePlacement,
  type LegacyPlacement,
  type Placement,
} from "@crosskit-ui/core";
import { usePresence } from "../usePresence";

const props = withDefaults(
  defineProps<{
    content?: string;
    /** Accepts Floating UI names and v0's Ant names (`topLeft`, `rightBottom`, …). */
    placement?: Placement | LegacyPlacement;
    open?: boolean;
    defaultOpen?: boolean;
    openDelay?: number;
    closeDelay?: number;
    disabled?: boolean;
    contentClass?: string;
    id?: string;
  }>(),
  {}
);

const emit = defineEmits<{ "update:open": [boolean]; openChange: [{ open: boolean }] }>();

const autoId = useId();

// @zag-js/vue takes a GETTER, not an object, so prop changes stay reactive.
const machineProps = computed(() => ({
  id: props.id ?? autoId,
  open: props.open,
  defaultOpen: props.defaultOpen,
  openDelay: props.openDelay,
  closeDelay: props.closeDelay,
  disabled: props.disabled,
  positioning: { placement: resolvePlacement(props.placement) },
  onOpenChange(details: { open: boolean }) {
    emit("update:open", details.open);
    emit("openChange", details);
  },
}));
const service = useMachine(tooltip.machine, machineProps);
const api = computed(() => tooltip.connect(service, normalizeProps));
const presence = usePresence(() => api.value.open);

// focus/blur do not bubble to a wrapper, so focusin/focusout stand in. React's
// synthetic events fake the bubbling and would have hidden this divergence.
function onFocusIn(event: FocusEvent) {
  if (isFocusVisible(event.target)) api.value.setOpen(true);
}
</script>

<template>
  <span v-bind="api.getTriggerProps()" @focusin="onFocusIn" @focusout="api.setOpen(false)">
    <slot />
  </span>
  <!-- Gate on presence, NEVER on api.open, or [data-state="closed"] never gets
       a frame and the exit animation silently does nothing. -->
  <Teleport v-if="presence.present.value" to="body">
    <div v-bind="api.getPositionerProps()">
      <div
        :ref="el => presence.setNode(el as HTMLElement | null)"
        v-bind="api.getContentProps()"
        :class="props.contentClass"
      >
        <slot name="content">{{ props.content }}</slot>
      </div>
    </div>
  </Teleport>
</template>
