// packages/svelte/src/toast/ToastItem.svelte
<script lang="ts">
  import * as toast from "@zag-js/toast";
  import { useMachine, normalizeProps } from "@zag-js/svelte";
  import type { IconName } from "@crosskit-ui/core";
  import Icon from "../icon/Icon.svelte";

  // Same mapping as Alert, so a success toast and a success alert look alike.
  const ICON_FOR: Record<string, IconName> = {
    success: "check",
    error: "error",
    warning: "warning",
    info: "info",
  };

  interface Props {
    item: toast.Props;
    index: number;
    parent: toast.GroupService;
    hideIcon?: boolean;
  }

  let { item, index, parent, hideIcon }: Props = $props();

  const service = useMachine(toast.machine, () => ({ ...item, parent, index }));
  const api = $derived(toast.connect(service, normalizeProps));
  const icon = $derived(ICON_FOR[api.type]);
</script>

<div {...api.getRootProps()}>
  {#if !hideIcon && icon}
    <Icon name={icon} data-part="icon" />
  {/if}
  {#if api.title != null}
    <h3 {...api.getTitleProps()}>{api.title}</h3>
  {/if}
  {#if api.description != null}
    <p {...api.getDescriptionProps()}>{api.description}</p>
  {/if}
  <!-- The action lives on the toast's own options, not on the api — the api
       only supplies the trigger's props and click handling. -->
  {#if item.action}
    <button {...api.getActionTriggerProps()}>{item.action.label}</button>
  {/if}
  {#if api.closable}
    <button {...api.getCloseTriggerProps()} aria-label="Dismiss">
      <Icon name="close" size="sm" />
    </button>
  {/if}
</div>

// packages/vue/src/toast/ToastItem.vue
<script setup lang="ts">
import { computed } from "vue";
import * as toast from "@zag-js/toast";
import { useMachine, normalizeProps } from "@zag-js/vue";
import type { IconName } from "@crosskit-ui/core";
import Icon from "../icon/Icon.vue";

// Same mapping as Alert, so a success toast and a success alert look alike.
const ICON_FOR: Record<string, IconName> = {
  success: "check",
  error: "error",
  warning: "warning",
  info: "info",
};

const props = defineProps<{
  item: toast.Props;
  index: number;
  parent: toast.GroupService;
  hideIcon?: boolean;
}>();

// @zag-js/vue takes a GETTER, not an object, so prop changes stay reactive.
const machineProps = computed(() => ({
  ...props.item,
  parent: props.parent,
  index: props.index,
}));
const service = useMachine(toast.machine, machineProps);
const api = computed(() => toast.connect(service, normalizeProps));
const icon = computed(() => ICON_FOR[api.value.type]);
</script>

<template>
  <div v-bind="api.getRootProps()">
    <Icon v-if="!props.hideIcon && icon" :name="icon" data-part="icon" />
    <h3 v-if="api.title != null" v-bind="api.getTitleProps()">{{ api.title }}</h3>
    <p v-if="api.description != null" v-bind="api.getDescriptionProps()">{{ api.description }}</p>
    <!-- The action lives on the toast's own options, not on the api — the api
         only supplies the trigger's props and click handling. -->
    <button v-if="props.item.action" v-bind="api.getActionTriggerProps()">
      {{ props.item.action.label }}
    </button>
    <button v-if="api.closable" v-bind="api.getCloseTriggerProps()" aria-label="Dismiss">
      <Icon name="close" size="sm" />
    </button>
  </div>
</template>
