// packages/svelte/src/toggle/Switch.svelte
<script lang="ts">
  import type { Snippet } from "svelte";
  import type { HTMLInputAttributes } from "svelte/elements";
  import { dataAttr, type Size } from "@crosskit-ui/core";

  interface Props extends Omit<HTMLInputAttributes, "size" | "type"> {
    size?: Size;
    label?: string;
    checked?: boolean;
    children?: Snippet;
  }

  let {
    size = "md",
    label,
    checked = $bindable(false),
    disabled = false,
    id,
    children,
    class: klass,
    ...rest
  }: Props = $props();

  const uid = $props.id();
  const inputId = $derived(id ?? uid);
</script>

<!-- One real checkbox, one change event. v0 combined a wrapper onClick that
     synthesised a fake event with an inner onChange, so a single interaction
     could fire twice with different payload shapes. -->
<label
  data-scope="switch"
  data-part="root"
  data-disabled={dataAttr(disabled)}
  for={inputId}
  class={klass}
>
  <input
    id={inputId}
    type="checkbox"
    role="switch"
    data-part="hidden-input"
    {disabled}
    bind:checked
    {...rest}
  />
  <span data-part="control" data-size={size}>
    <span data-part="thumb"></span>
  </span>
  {#if label || children}
    <span data-part="label">{#if children}{@render children()}{:else}{label}{/if}</span>
  {/if}
</label>

// packages/vue/src/toggle/Switch.vue
<script setup lang="ts">
import { computed, useId } from "vue";
import { dataAttr, type Size } from "@crosskit-ui/core";

const props = withDefaults(
  defineProps<{
    size?: Size;
    label?: string;
    disabled?: boolean;
    id?: string;
    modelValue?: boolean;
    name?: string;
  }>(),
  { size: "md", disabled: false }
);

const emit = defineEmits<{ "update:modelValue": [boolean] }>();

const autoId = useId();
const inputId = computed(() => props.id ?? autoId);
</script>

<!-- One real checkbox, one change event. v0 combined a wrapper onClick that
     synthesised a fake event with an inner onChange, so a single interaction
     could fire twice with different payload shapes. -->
<template>
  <label
    data-scope="switch"
    data-part="root"
    :data-disabled="dataAttr(props.disabled)"
    :for="inputId"
  >
    <input
      :id="inputId"
      type="checkbox"
      role="switch"
      data-part="hidden-input"
      :disabled="props.disabled"
      :checked="props.modelValue"
      :name="props.name"
      @change="emit('update:modelValue', ($event.target as HTMLInputElement).checked)"
    />
    <span data-part="control" :data-size="props.size">
      <span data-part="thumb" />
    </span>
    <span v-if="props.label || $slots.default" data-part="label">
      <slot>{{ props.label }}</slot>
    </span>
  </label>
</template>
