// packages/react/src/button/button.tsx
// NO "use client": a Button is server-safe. A consumer's own onClick is THEIR
// client boundary, not ours — putting a directive here would needlessly pull
// every consuming tree into the client bundle.
import type { ButtonHTMLAttributes, ReactNode, Ref } from "react";
import { dataAttr, type IconName, type Size, type Variant } from "@crosskit-ui/core";
import { Icon } from "../icon/icon";

export interface ButtonProps extends Omit<ButtonHTMLAttributes<HTMLButtonElement>, "type"> {
  variant?: Variant;
  size?: Size;
  loading?: boolean;
  fullWidth?: boolean;
  icon?: IconName;
  iconPosition?: "left" | "right";
  /**
   * Defaults to "button". The v0 component had no default, so a Button inside a
   * <form> silently acted as submit. See MIGRATION.md.
   */
  type?: "button" | "submit" | "reset";
  children?: ReactNode;
  ref?: Ref<HTMLButtonElement>;
}

export function Button({
  variant = "primary",
  size = "md",
  loading = false,
  fullWidth = false,
  icon,
  iconPosition = "left",
  type = "button",
  disabled,
  children,
  className,
  ref,
  ...rest
}: ButtonProps) {
  const iconEl = icon ? <Icon name={icon} size={size} data-part="icon" /> : null;

  return (
    <button
      ref={ref}
      type={type}
      data-scope="button"
      data-part="root"
      data-variant={variant}
      data-size={size}
      data-loading={dataAttr(loading)}
      data-disabled={dataAttr(disabled)}
      data-full-width={dataAttr(fullWidth)}
      data-icon-position={icon ? iconPosition : undefined}
      disabled={disabled || loading}
      className={className}
      // rest LAST so consumers (and composing components) can override anything
      {...rest}
    >
      {iconPosition === "left" && iconEl}
      {children != null && <span data-part="label">{children}</span>}
      {iconPosition === "right" && iconEl}
    </button>
  );
}

// packages/vue/src/button/Button.vue
<script setup lang="ts">
import { dataAttr, type IconName, type Size, type Variant } from "@crosskit-ui/core";
import Icon from "../icon/Icon.vue";
import Spinner from "../spinner/Spinner.vue";

const props = withDefaults(
  defineProps<{
    variant?: Variant;
    size?: Size;
    loading?: boolean;
    fullWidth?: boolean;
    icon?: IconName;
    iconPosition?: "left" | "right";
    type?: "button" | "submit" | "reset";
    disabled?: boolean;
  }>(),
  {
    variant: "primary",
    size: "md",
    loading: false,
    fullWidth: false,
    iconPosition: "left",
    type: "button",
    disabled: false,
  }
);

// inheritAttrs defaults to true, and THAT is the className passthrough: a
// consumer's class/id/@click land on the root <button> with no plumbing. We
// deliberately declare no `class` prop.
</script>

<template>
  <button
    :type="props.type"
    data-scope="button"
    data-part="root"
    :data-variant="props.variant"
    :data-size="props.size"
    :data-loading="dataAttr(props.loading)"
    :data-disabled="dataAttr(props.disabled)"
    :data-full-width="dataAttr(props.fullWidth)"
    :data-icon-position="props.icon ? props.iconPosition : undefined"
    :disabled="props.disabled || props.loading"
  >
    <Spinner v-if="props.loading" :size="props.size" label="" />
    <Icon
      v-if="props.icon && props.iconPosition === 'left'"
      :name="props.icon"
      :size="props.size"
    />
    <span v-if="$slots.default" data-part="label"><slot /></span>
    <Icon
      v-if="props.icon && props.iconPosition === 'right'"
      :name="props.icon"
      :size="props.size"
    />
  </button>
</template>
