// packages/react/src/accordion/accordion.tsx
"use client";

import { useId, type ReactNode } from "react";
import * as accordion from "@zag-js/accordion";
import { useMachine, normalizeProps } from "@zag-js/react";
import { Icon } from "../icon/icon";

export interface AccordionItem {
  id: string;
  title: ReactNode;
  content: ReactNode;
  disabled?: boolean;
}

export interface AccordionProps {
  items: AccordionItem[];
  value?: string[];
  defaultValue?: string[];
  onValueChange?: (details: { value: string[] }) => void;
  /** v0 called this `multiple`. */
  allowMultiple?: boolean;
  /** Allow closing the open item, leaving none open. */
  collapsible?: boolean;
  id?: string;
  className?: string;
}

export function Accordion({
  items,
  allowMultiple = false,
  collapsible = true,
  id,
  className,
  ...machineProps
}: AccordionProps) {
  const autoId = useId();
  const service = useMachine(accordion.machine, {
    id: id ?? autoId,
    multiple: allowMultiple,
    collapsible,
    ...machineProps,
  });
  const api = accordion.connect(service, normalizeProps);

  return (
    <div {...api.getRootProps()} className={className}>
      {items.map(item => {
        const itemProps = { value: item.id, disabled: item.disabled };
        return (
          <div key={item.id} {...api.getItemProps(itemProps)}>
            <h3>
              <button {...api.getItemTriggerProps(itemProps)}>
                {item.title}
                {/* The chevron rotates off the machine's own data-state, so
                    there is no JS toggling a class. */}
                <Icon name="chevronDown" size="sm" data-part="item-indicator" />
              </button>
            </h3>
            <div {...api.getItemContentProps(itemProps)}>{item.content}</div>
          </div>
        );
      })}
    </div>
  );
}

// packages/vue/src/accordion/Accordion.vue
<script setup lang="ts">
import { computed, useId } from "vue";
import * as accordion from "@zag-js/accordion";
import { useMachine, normalizeProps } from "@zag-js/vue";
import Icon from "../icon/Icon.vue";

export interface AccordionItem {
  id: string;
  title: string;
  disabled?: boolean;
}

const props = withDefaults(
  defineProps<{
    items: AccordionItem[];
    value?: string[];
    defaultValue?: string[];
    allowMultiple?: boolean;
    collapsible?: boolean;
    id?: string;
  }>(),
  { allowMultiple: false, collapsible: true }
);

const emit = defineEmits<{ "update:value": [string[]]; valueChange: [{ value: string[] }] }>();

const autoId = useId();
const machineProps = computed(() => ({
  id: props.id ?? autoId,
  multiple: props.allowMultiple,
  collapsible: props.collapsible,
  value: props.value,
  defaultValue: props.defaultValue,
  onValueChange(details: { value: string[] }) {
    emit("update:value", details.value);
    emit("valueChange", details);
  },
}));
const service = useMachine(accordion.machine, machineProps);
const api = computed(() => accordion.connect(service, normalizeProps));
</script>

<template>
  <div v-bind="api.getRootProps()">
    <div
      v-for="item in props.items"
      :key="item.id"
      v-bind="api.getItemProps({ value: item.id, disabled: item.disabled })"
    >
      <h3>
        <button v-bind="api.getItemTriggerProps({ value: item.id, disabled: item.disabled })">
          <slot :name="`title-${item.id}`">{{ item.title }}</slot>
          <!-- rotates off the machine's own data-state; no JS toggling a class -->
          <Icon name="chevronDown" size="sm" data-part="item-indicator" />
        </button>
      </h3>
      <div v-bind="api.getItemContentProps({ value: item.id, disabled: item.disabled })">
        <slot :name="item.id" />
      </div>
    </div>
  </div>
</template>
