// packages/vue/src/divider/Divider.vue
<script setup lang="ts">
import { useSlots } from "vue";
import { dataAttr, type Orientation } from "@crosskit-ui/core";

const props = withDefaults(
  defineProps<{
    orientation?: Orientation;
    align?: "start" | "center" | "end";
    dashed?: boolean;
  }>(),
  { orientation: "horizontal", align: "center", dashed: false }
);

const slots = useSlots();
</script>

<template>
  <div
    role="separator"
    :aria-orientation="props.orientation"
    data-scope="divider"
    data-part="root"
    :data-orientation="props.orientation"
    :data-align="props.align"
    :data-dashed="dataAttr(props.dashed)"
  >
    <template v-if="props.orientation === 'horizontal'">
      <span data-part="line" />
      <template v-if="slots.default">
        <span data-part="label"><slot /></span>
        <span data-part="line" />
      </template>
    </template>
  </div>
</template>

// packages/svelte/src/divider/Divider.svelte
<script lang="ts">
  import type { Snippet } from "svelte";
  import type { HTMLAttributes } from "svelte/elements";
  import { dataAttr, type Orientation } from "@crosskit-ui/core";

  interface Props extends HTMLAttributes<HTMLDivElement> {
    orientation?: Orientation;
    align?: "start" | "center" | "end";
    dashed?: boolean;
    children?: Snippet;
  }

  let {
    orientation = "horizontal",
    align = "center",
    dashed = false,
    children,
    class: klass,
    ...rest
  }: Props = $props();
</script>

<div
  role="separator"
  aria-orientation={orientation}
  data-scope="divider"
  data-part="root"
  data-orientation={orientation}
  data-align={align}
  data-dashed={dataAttr(dashed)}
  class={klass}
  {...rest}
>
  {#if orientation === "horizontal"}
    <span data-part="line"></span>
    {#if children}
      <span data-part="label">{@render children()}</span>
      <span data-part="line"></span>
    {/if}
  {/if}
</div>
