// packages/react/src/layout/container.tsx
import type { HTMLAttributes, ReactNode, Ref } from "react";
import { dataAttr } from "@crosskit-ui/core";

export type ContainerMaxWidth = "sm" | "md" | "lg" | "xl" | "2xl" | "full" | "none";

export interface ContainerProps extends HTMLAttributes<HTMLDivElement> {
  maxWidth?: ContainerMaxWidth;
  padding?: boolean;
  center?: boolean;
  children?: ReactNode;
  ref?: Ref<HTMLDivElement>;
}

export function Container({
  maxWidth = "lg",
  padding = true,
  center = true,
  children,
  className,
  ref,
  ...rest
}: ContainerProps) {
  return (
    <div
      ref={ref}
      data-scope="container"
      data-part="root"
      data-max-width={maxWidth === "none" ? undefined : maxWidth}
      data-padded={dataAttr(padding)}
      data-centered={dataAttr(center)}
      className={className}
      {...rest}
    >
      {children}
    </div>
  );
}

// packages/vue/src/layout/Container.vue
<script setup lang="ts">
import { dataAttr } from "@crosskit-ui/core";

const props = withDefaults(
  defineProps<{
    maxWidth?: "sm" | "md" | "lg" | "xl" | "2xl" | "full" | "none";
    padding?: boolean;
    center?: boolean;
  }>(),
  { maxWidth: "lg", padding: true, center: true }
);
</script>

<template>
  <div
    data-scope="container"
    data-part="root"
    :data-max-width="props.maxWidth === 'none' ? undefined : props.maxWidth"
    :data-padded="dataAttr(props.padding)"
    :data-centered="dataAttr(props.center)"
  >
    <slot />
  </div>
</template>
