// packages/svelte/src/layout/Row.svelte
<script lang="ts">
  import type { Snippet } from "svelte";
  import type { HTMLAttributes } from "svelte/elements";
  import { dataAttr } from "@crosskit-ui/core";

  interface Props extends HTMLAttributes<HTMLDivElement> {
    justify?: "start" | "center" | "end" | "between" | "around" | "evenly";
    align?: "start" | "center" | "end" | "stretch" | "baseline";
    spacing?: number;
    wrap?: boolean;
    reverse?: boolean;
    children?: Snippet;
  }

  let {
    justify,
    align,
    spacing,
    wrap = true,
    reverse = false,
    children,
    class: klass,
    style,
    ...rest
  }: Props = $props();

  // Inline custom property, not a class: v0's `gap-${n}` was a dynamic Tailwind
  // class that produced nothing in a consumer's build.
  const styleAttr = $derived(
    spacing == null ? style : `${style ? style + ";" : ""}--ck-row-spacing:${spacing}`,
  );
</script>

<div
  data-scope="row"
  data-part="root"
  data-justify={justify}
  data-align={align}
  data-wrap={wrap ? undefined : "false"}
  data-reverse={dataAttr(reverse)}
  class={klass}
  style={styleAttr}
  {...rest}
>
  {@render children?.()}
</div>

// packages/vue/src/layout/Row.vue
<script setup lang="ts">
import { computed } from "vue";
import { dataAttr } from "@crosskit-ui/core";

const props = withDefaults(
  defineProps<{
    justify?: "start" | "center" | "end" | "between" | "around" | "evenly";
    align?: "start" | "center" | "end" | "stretch" | "baseline";
    spacing?: number;
    wrap?: boolean;
    reverse?: boolean;
  }>(),
  { wrap: true, reverse: false }
);

// Inline custom property, not a class: v0's `gap-${n}` was a dynamic Tailwind
// class that produced nothing in a consumer's build.
const style = computed(() =>
  props.spacing == null ? undefined : { "--ck-row-spacing": String(props.spacing) }
);
</script>

<template>
  <div
    data-scope="row"
    data-part="root"
    :data-justify="props.justify"
    :data-align="props.align"
    :data-wrap="props.wrap ? undefined : 'false'"
    :data-reverse="dataAttr(props.reverse)"
    :style="style"
  >
    <slot />
  </div>
</template>
