// packages/react/src/tooltip/tooltip.tsx
"use client";

import { useId, type ReactNode } from "react";
import * as tooltip from "@zag-js/tooltip";
import { useMachine, normalizeProps, Portal } from "@zag-js/react";
import {
  isFocusVisible,
  resolvePlacement,
  type LegacyPlacement,
  type Placement,
} from "@crosskit-ui/core";
import { usePresence } from "../use-presence";

export interface TooltipProps {
  content: ReactNode;
  children: ReactNode;
  /** Accepts Floating UI names and v0's Ant names (`topLeft`, `rightBottom`, …). */
  placement?: Placement | LegacyPlacement;
  /** v0 called this `visible`. */
  open?: boolean;
  defaultOpen?: boolean;
  onOpenChange?: (details: { open: boolean }) => void;
  /** v0 called this `showDelay`. */
  openDelay?: number;
  /** v0 called this `hideDelay`. */
  closeDelay?: number;
  disabled?: boolean;
  /** v0 called this `overlayClassName`. */
  contentClassName?: string;
  id?: string;
  className?: string;
}

export function Tooltip({
  content,
  children,
  placement,
  openDelay,
  closeDelay,
  disabled,
  contentClassName,
  id,
  className,
  ...machineProps
}: TooltipProps) {
  // Unconditional: `id ?? useId()` would be a conditional hook call.
  const autoId = useId();
  const service = useMachine(tooltip.machine, {
    id: id ?? autoId,
    openDelay,
    closeDelay,
    disabled,
    positioning: { placement: resolvePlacement(placement) },
    ...machineProps,
  });
  const api = tooltip.connect(service, normalizeProps);
  const { present, setNode } = usePresence(api.open);

  return (
    <>
      {/* The trigger wraps rather than clones, so the consumer's element is
          untouched. focusin/focusout stand in for zag's focus/blur, which do
          not bubble up to a wrapper — see the note in overlay.css for why the
          wrapper is a real box and not display:contents. */}
      <span
        {...api.getTriggerProps()}
        className={className}
        onFocus={e => {
          if (isFocusVisible(e.target)) api.setOpen(true);
        }}
        onBlur={() => api.setOpen(false)}
      >
        {children}
      </span>
      {/* Gate on presence, NEVER on api.open, or [data-state="closed"] never
          gets a frame and the exit animation silently does nothing. */}
      {present && (
        <Portal>
          <div {...api.getPositionerProps()}>
            <div ref={setNode} {...api.getContentProps()} className={contentClassName}>
              {content}
            </div>
          </div>
        </Portal>
      )}
    </>
  );
}

// packages/svelte/src/tooltip/Tooltip.svelte
<script lang="ts">
  import type { Snippet } from "svelte";
  import * as tooltip from "@zag-js/tooltip";
  import { useMachine, normalizeProps, portal } from "@zag-js/svelte";
  import {
    isFocusVisible,
    resolvePlacement,
    type LegacyPlacement,
    type Placement,
  } from "@crosskit-ui/core";
  import { usePresence, presenceNode } from "../presence.svelte";

  interface Props {
    content?: string | Snippet;
    /** Accepts Floating UI names and v0's Ant names (`topLeft`, `rightBottom`, …). */
    placement?: Placement | LegacyPlacement;
    open?: boolean;
    defaultOpen?: boolean;
    onOpenChange?: (details: { open: boolean }) => void;
    openDelay?: number;
    closeDelay?: number;
    disabled?: boolean;
    class?: string;
    contentClass?: string;
    id?: string;
    children?: Snippet;
  }

  let {
    content,
    placement,
    open = $bindable(undefined),
    defaultOpen,
    onOpenChange,
    openDelay,
    closeDelay,
    disabled,
    class: klass,
    contentClass,
    id,
    children,
  }: Props = $props();

  const uid = $props.id();

  const service = useMachine(tooltip.machine, () => ({
    id: id ?? uid,
    open,
    defaultOpen,
    openDelay,
    closeDelay,
    disabled,
    positioning: { placement: resolvePlacement(placement) },
    onOpenChange(details: { open: boolean }) {
      open = details.open;
      onOpenChange?.(details);
    },
  }));

  const api = $derived(tooltip.connect(service, normalizeProps));
  const presence = usePresence(() => ({ present: api.open }));

  // zag types the trigger through normalize.button; this one lands on a <span>,
  // so the props are widened rather than the element being changed.
  const triggerProps = $derived(api.getTriggerProps() as Record<string, unknown>);
</script>

<!-- focus/blur do not bubble to a wrapper, so focusin/focusout stand in. React's
     synthetic events fake the bubbling and would have hidden this divergence. -->
<span
  {...triggerProps}
  class={klass}
  onfocusin={e => {
    if (isFocusVisible(e.target)) api.setOpen(true);
  }}
  onfocusout={() => api.setOpen(false)}
>
  {@render children?.()}
</span>

<!-- Gate on presence, NEVER on api.open, or [data-state="closed"] never gets a
     frame and the exit animation silently does nothing. -->
{#if presence.present}
  <div use:portal {...api.getPositionerProps()}>
    <div {...api.getContentProps()} class={contentClass} use:presenceNode={presence.setNode}>
      {#if typeof content === "string"}{content}{:else}{@render content?.()}{/if}
    </div>
  </div>
{/if}
