// packages/react/src/toggle/checkbox.tsx
import {
  useEffect,
  useId,
  useRef,
  type InputHTMLAttributes,
  type ReactNode,
  type Ref,
} from "react";
import { ariaAttr, dataAttr, type Size } from "@crosskit-ui/core";

export interface CheckboxProps extends Omit<
  InputHTMLAttributes<HTMLInputElement>,
  "size" | "type"
> {
  size?: Size;
  label?: ReactNode;
  invalid?: boolean;
  /** Renders the mixed state. This is a DOM *property*, not an attribute. */
  indeterminate?: boolean;
  ref?: Ref<HTMLInputElement>;
}

export function Checkbox({
  size = "md",
  label,
  invalid = false,
  indeterminate = false,
  disabled,
  id,
  className,
  ref,
  ...rest
}: CheckboxProps) {
  const autoId = useId();
  const inputId = id ?? autoId;
  const innerRef = useRef<HTMLInputElement>(null);

  // `indeterminate` has no HTML attribute — it exists only as a DOM property,
  // which is why it needs an effect rather than a prop on the element.
  useEffect(() => {
    if (innerRef.current) innerRef.current.indeterminate = indeterminate;
  }, [indeterminate]);

  return (
    <label
      data-scope="checkbox"
      data-part="root"
      data-disabled={dataAttr(disabled)}
      data-invalid={dataAttr(invalid)}
      htmlFor={inputId}
      className={className}
    >
      <input
        ref={node => {
          innerRef.current = node;
          if (typeof ref === "function") ref(node);
          else if (ref) ref.current = node;
        }}
        id={inputId}
        type="checkbox"
        data-part="control"
        data-size={size}
        disabled={disabled}
        aria-invalid={ariaAttr(invalid)}
        {...rest}
      />
      {label != null && <span data-part="label">{label}</span>}
    </label>
  );
}

// packages/svelte/src/toggle/Checkbox.svelte
<script lang="ts">
  import type { Snippet } from "svelte";
  import type { HTMLInputAttributes } from "svelte/elements";
  import { ariaAttr, dataAttr, type Size } from "@crosskit-ui/core";

  interface Props extends Omit<HTMLInputAttributes, "size" | "type"> {
    size?: Size;
    label?: string;
    invalid?: boolean;
    indeterminate?: boolean;
    checked?: boolean;
    children?: Snippet;
  }

  let {
    size = "md",
    label,
    invalid = false,
    indeterminate = $bindable(false),
    checked = $bindable(false),
    disabled = false,
    id,
    children,
    class: klass,
    ...rest
  }: Props = $props();

  const uid = $props.id();
  const inputId = $derived(id ?? uid);
</script>

<label
  data-scope="checkbox"
  data-part="root"
  data-disabled={dataAttr(disabled)}
  data-invalid={dataAttr(invalid)}
  for={inputId}
  class={klass}
>
  <!-- `indeterminate` has no HTML attribute, but Svelte binds the DOM property
       directly, so no effect is needed here as it is in React and Vue. -->
  <input
    id={inputId}
    type="checkbox"
    data-part="control"
    data-size={size}
    {disabled}
    aria-invalid={ariaAttr(invalid)}
    bind:checked
    bind:indeterminate
    {...rest}
  />
  {#if label || children}
    <span data-part="label">{#if children}{@render children()}{:else}{label}{/if}</span>
  {/if}
</label>
