// packages/react/src/toggle/radio.tsx
import { useId, type InputHTMLAttributes, type ReactNode, type Ref } from "react";
import { ariaAttr, dataAttr, type Orientation, type Size } from "@crosskit-ui/core";

export interface RadioProps extends Omit<InputHTMLAttributes<HTMLInputElement>, "size" | "type"> {
  size?: Size;
  label?: ReactNode;
  invalid?: boolean;
  ref?: Ref<HTMLInputElement>;
}

export function Radio({
  size = "md",
  label,
  invalid = false,
  disabled,
  id,
  className,
  ref,
  ...rest
}: RadioProps) {
  const autoId = useId();
  const inputId = id ?? autoId;

  return (
    <label
      data-scope="radio"
      data-part="root"
      data-disabled={dataAttr(disabled)}
      data-invalid={dataAttr(invalid)}
      htmlFor={inputId}
      className={className}
    >
      <input
        ref={ref}
        id={inputId}
        type="radio"
        data-part="control"
        data-size={size}
        disabled={disabled}
        aria-invalid={ariaAttr(invalid)}
        {...rest}
      />
      {label != null && <span data-part="label">{label}</span>}
    </label>
  );
}

export interface RadioGroupProps {
  /** Shared `name`, which is what makes native radios mutually exclusive. */
  name?: string;
  orientation?: Orientation;
  label?: ReactNode;
  children?: ReactNode;
  className?: string;
}

/**
 * A grouping wrapper, not a controller. Native radios already handle selection
 * and arrow-key navigation once they share a `name`; this adds the group
 * semantics screen readers need, which v0 never provided.
 */
export function RadioGroup({
  name,
  orientation = "horizontal",
  label,
  children,
  className,
}: RadioGroupProps) {
  return (
    <div
      role="radiogroup"
      aria-label={typeof label === "string" ? label : undefined}
      data-scope="radio-group"
      data-part="root"
      data-orientation={orientation}
      data-name={name}
      className={className}
    >
      {children}
    </div>
  );
}

// packages/svelte/src/toggle/Radio.svelte
<script lang="ts">
  import type { Snippet } from "svelte";
  import type { HTMLInputAttributes } from "svelte/elements";
  import { ariaAttr, dataAttr, type Size } from "@crosskit-ui/core";

  interface Props extends Omit<HTMLInputAttributes, "size" | "type"> {
    size?: Size;
    label?: string;
    invalid?: boolean;
    group?: string;
    children?: Snippet;
  }

  let {
    size = "md",
    label,
    invalid = false,
    group = $bindable(),
    value,
    disabled = false,
    id,
    children,
    class: klass,
    ...rest
  }: Props = $props();

  const uid = $props.id();
  const inputId = $derived(id ?? uid);
</script>

<label
  data-scope="radio"
  data-part="root"
  data-disabled={dataAttr(disabled)}
  data-invalid={dataAttr(invalid)}
  for={inputId}
  class={klass}
>
  <!-- bind:group is Svelte's native radio idiom — the direct analogue of
       React's shared `name` and Vue's v-model. -->
  <input
    id={inputId}
    type="radio"
    data-part="control"
    data-size={size}
    {disabled}
    {value}
    aria-invalid={ariaAttr(invalid)}
    bind:group
    {...rest}
  />
  {#if label || children}
    <span data-part="label"
      >{#if children}{@render children()}{:else}{label}{/if}</span
    >
  {/if}
</label>
