// packages/vue/src/toggle/Radio.vue
<script setup lang="ts">
import { computed, useId } from "vue";
import { ariaAttr, dataAttr, type Size } from "@crosskit-ui/core";

const props = withDefaults(
  defineProps<{
    size?: Size;
    label?: string;
    invalid?: boolean;
    disabled?: boolean;
    id?: string;
    value?: string;
    name?: string;
    modelValue?: string;
  }>(),
  { size: "md", invalid: false, disabled: false }
);

const emit = defineEmits<{ "update:modelValue": [string] }>();

const autoId = useId();
const inputId = computed(() => props.id ?? autoId);
</script>

<template>
  <label
    data-scope="radio"
    data-part="root"
    :data-disabled="dataAttr(props.disabled)"
    :data-invalid="dataAttr(props.invalid)"
    :for="inputId"
  >
    <input
      :id="inputId"
      type="radio"
      data-part="control"
      :data-size="props.size"
      :disabled="props.disabled"
      :aria-invalid="ariaAttr(props.invalid)"
      :value="props.value"
      :name="props.name"
      :checked="props.modelValue === props.value"
      @change="emit('update:modelValue', ($event.target as HTMLInputElement).value)"
    />
    <span v-if="props.label || $slots.default" data-part="label">
      <slot>{{ props.label }}</slot>
    </span>
  </label>
</template>

// packages/svelte/src/toggle/Radio.svelte
<script lang="ts">
  import type { Snippet } from "svelte";
  import type { HTMLInputAttributes } from "svelte/elements";
  import { ariaAttr, dataAttr, type Size } from "@crosskit-ui/core";

  interface Props extends Omit<HTMLInputAttributes, "size" | "type"> {
    size?: Size;
    label?: string;
    invalid?: boolean;
    group?: string;
    children?: Snippet;
  }

  let {
    size = "md",
    label,
    invalid = false,
    group = $bindable(),
    value,
    disabled = false,
    id,
    children,
    class: klass,
    ...rest
  }: Props = $props();

  const uid = $props.id();
  const inputId = $derived(id ?? uid);
</script>

<label
  data-scope="radio"
  data-part="root"
  data-disabled={dataAttr(disabled)}
  data-invalid={dataAttr(invalid)}
  for={inputId}
  class={klass}
>
  <!-- bind:group is Svelte's native radio idiom — the direct analogue of
       React's shared `name` and Vue's v-model. -->
  <input
    id={inputId}
    type="radio"
    data-part="control"
    data-size={size}
    {disabled}
    {value}
    aria-invalid={ariaAttr(invalid)}
    bind:group
    {...rest}
  />
  {#if label || children}
    <span data-part="label"
      >{#if children}{@render children()}{:else}{label}{/if}</span
    >
  {/if}
</label>
