// packages/vue/src/toggle/RadioGroup.vue
<script setup lang="ts">
import type { Orientation } from "@crosskit-ui/core";

const props = withDefaults(defineProps<{ orientation?: Orientation; label?: string }>(), {
  orientation: "horizontal",
});
</script>

<!-- A grouping wrapper, not a controller: native radios already handle
     selection and arrow-key navigation once they share a `name`. This supplies
     the group semantics screen readers need, which v0 never provided. -->
<template>
  <div
    role="radiogroup"
    :aria-label="props.label"
    data-scope="radio-group"
    data-part="root"
    :data-orientation="props.orientation"
  >
    <slot />
  </div>
</template>

// packages/svelte/src/toggle/RadioGroup.svelte
<script lang="ts">
  import type { Snippet } from "svelte";
  import type { Orientation } from "@crosskit-ui/core";

  interface Props {
    orientation?: Orientation;
    label?: string;
    children?: Snippet;
    class?: string;
  }

  let { orientation = "horizontal", label, children, class: klass }: Props = $props();
</script>

<!-- A grouping wrapper, not a controller: bind:group already handles selection
     and arrow-key navigation. This supplies the group semantics screen readers
     need, which v0 never provided. -->
<div
  role="radiogroup"
  aria-label={label}
  data-scope="radio-group"
  data-part="root"
  data-orientation={orientation}
  class={klass}
>
  {@render children?.()}
</div>
