// packages/vue/src/badge/Badge.vue
<script setup lang="ts">
import { dataAttr, type Size, type Status } from "@crosskit-ui/core";

const props = withDefaults(
  defineProps<{
    variant?: "primary" | "secondary" | Status;
    size?: Size;
    rounded?: boolean;
    outlined?: boolean;
  }>(),
  { variant: "primary", size: "md", rounded: false, outlined: false }
);
</script>

<template>
  <span
    data-scope="badge"
    data-part="root"
    :data-variant="props.variant"
    :data-size="props.size"
    :data-rounded="dataAttr(props.rounded)"
    :data-outlined="dataAttr(props.outlined)"
  >
    <slot />
  </span>
</template>

// packages/react/src/badge/badge.tsx
import type { HTMLAttributes, ReactNode, Ref } from "react";
import { dataAttr, type Size, type Status } from "@crosskit-ui/core";

export type BadgeVariant = "primary" | "secondary" | Status;

export interface BadgeProps extends HTMLAttributes<HTMLSpanElement> {
  variant?: BadgeVariant;
  size?: Size;
  rounded?: boolean;
  outlined?: boolean;
  children?: ReactNode;
  ref?: Ref<HTMLSpanElement>;
}

export function Badge({
  variant = "primary",
  size = "md",
  rounded = false,
  outlined = false,
  children,
  className,
  ref,
  ...rest
}: BadgeProps) {
  return (
    <span
      ref={ref}
      data-scope="badge"
      data-part="root"
      data-variant={variant}
      data-size={size}
      data-rounded={dataAttr(rounded)}
      data-outlined={dataAttr(outlined)}
      className={className}
      {...rest}
    >
      {children}
    </span>
  );
}
