// packages/vue/src/badge/Badge.vue
<script setup lang="ts">
import { dataAttr, type Size, type Status } from "@crosskit-ui/core";

const props = withDefaults(
  defineProps<{
    variant?: "primary" | "secondary" | Status;
    size?: Size;
    rounded?: boolean;
    outlined?: boolean;
  }>(),
  { variant: "primary", size: "md", rounded: false, outlined: false }
);
</script>

<template>
  <span
    data-scope="badge"
    data-part="root"
    :data-variant="props.variant"
    :data-size="props.size"
    :data-rounded="dataAttr(props.rounded)"
    :data-outlined="dataAttr(props.outlined)"
  >
    <slot />
  </span>
</template>

// packages/angular/src/feedback/badge.component.ts
import { booleanAttribute, ChangeDetectionStrategy, Component, input } from "@angular/core";
import type { Size, Status } from "@crosskit-ui/core";
import { ckDataAttr } from "@crosskit-ui/zag-angular";

@Component({
  selector: "ck-badge, span[ckBadge]",
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: {
    "data-scope": "badge",
    "data-part": "root",
    "[attr.data-variant]": "variant()",
    "[attr.data-size]": "size()",
    "[attr.data-rounded]": "attr(rounded())",
    "[attr.data-outlined]": "attr(outlined())",
  },
  template: `<ng-content />`,
})
export class CkBadge {
  readonly variant = input<"primary" | "secondary" | Status>("primary");
  readonly size = input<Size>("md");
  readonly rounded = input(false, { transform: booleanAttribute });
  readonly outlined = input(false, { transform: booleanAttribute });
  protected readonly attr = ckDataAttr;
}
