// packages/vue/src/divider/Divider.vue
<script setup lang="ts">
import { useSlots } from "vue";
import { dataAttr, type Orientation } from "@crosskit-ui/core";

const props = withDefaults(
  defineProps<{
    orientation?: Orientation;
    align?: "start" | "center" | "end";
    dashed?: boolean;
  }>(),
  { orientation: "horizontal", align: "center", dashed: false }
);

const slots = useSlots();
</script>

<template>
  <div
    role="separator"
    :aria-orientation="props.orientation"
    data-scope="divider"
    data-part="root"
    :data-orientation="props.orientation"
    :data-align="props.align"
    :data-dashed="dataAttr(props.dashed)"
  >
    <template v-if="props.orientation === 'horizontal'">
      <span data-part="line" />
      <template v-if="slots.default">
        <span data-part="label"><slot /></span>
        <span data-part="line" />
      </template>
    </template>
  </div>
</template>

// packages/angular/src/feedback/divider.component.ts
import { booleanAttribute, ChangeDetectionStrategy, Component, input } from "@angular/core";
import type { Orientation } from "@crosskit-ui/core";
import { ckDataAttr } from "@crosskit-ui/zag-angular";

@Component({
  selector: "ck-divider",
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: {
    role: "separator",
    "[attr.aria-orientation]": "orientation()",
    "data-scope": "divider",
    "data-part": "root",
    "[attr.data-orientation]": "orientation()",
    "[attr.data-align]": "align()",
    "[attr.data-dashed]": "attr(dashed())",
  },
  template: `
    @if (orientation() === "horizontal") {
      <span data-part="line"></span>
      @if (label()) {
        <span data-part="label">{{ label() }}</span>
        <span data-part="line"></span>
      }
    }
  `,
})
export class CkDivider {
  readonly orientation = input<Orientation>("horizontal");
  readonly align = input<"start" | "center" | "end">("center");
  readonly dashed = input(false, { transform: booleanAttribute });
  /** Angular cannot conditionally wrap projected content, so the label is a prop. */
  readonly label = input<string>();
  protected readonly attr = ckDataAttr;
}
