// packages/vue/src/textarea/Textarea.vue
<script setup lang="ts">
import { computed, useId } from "vue";
import { ariaAttr, dataAttr, type FieldVariant, type Size } from "@crosskit-ui/core";

const props = withDefaults(
  defineProps<{
    variant?: FieldVariant;
    size?: Size;
    label?: string;
    helperText?: string;
    invalid?: boolean;
    errorMessage?: string;
    autoResize?: boolean;
    fullWidth?: boolean;
    disabled?: boolean;
    id?: string;
    modelValue?: string;
  }>(),
  {
    variant: "default",
    size: "md",
    invalid: false,
    autoResize: false,
    fullWidth: true,
    disabled: false,
  }
);

const emit = defineEmits<{ "update:modelValue": [string] }>();

const autoId = useId();
const textareaId = computed(() => props.id ?? autoId);
const describedBy = computed(() =>
  props.errorMessage
    ? `${textareaId.value}-error`
    : props.helperText
      ? `${textareaId.value}-helper`
      : undefined
);

// Auto-resize is CSS. This only mirrors the value onto the wrapper so the
// invisible replica can size the grid cell — one DOM write, no measurement.
function onInput(event: Event) {
  const el = event.target as HTMLTextAreaElement;
  if (props.autoResize) el.parentElement?.setAttribute("data-value", el.value);
  emit("update:modelValue", el.value);
}
</script>

<template>
  <div
    data-scope="textarea"
    data-part="field"
    :data-variant="props.variant"
    :data-invalid="dataAttr(props.invalid)"
    :data-full-width="dataAttr(props.fullWidth)"
  >
    <label v-if="props.label" data-part="label" :for="textareaId">{{ props.label }}</label>
    <div
      data-scope="textarea"
      data-part="control"
      :data-auto-resize="dataAttr(props.autoResize)"
      :data-value="props.autoResize ? (props.modelValue ?? '') : undefined"
    >
      <textarea
        :id="textareaId"
        data-scope="textarea"
        data-part="input"
        :data-size="props.size"
        :disabled="props.disabled"
        :aria-invalid="ariaAttr(props.invalid)"
        :aria-describedby="describedBy"
        :value="props.modelValue"
        @input="onInput"
      />
    </div>
    <p v-if="props.errorMessage" :id="`${textareaId}-error`" data-part="error-text">
      {{ props.errorMessage }}
    </p>
    <p v-else-if="props.helperText" :id="`${textareaId}-helper`" data-part="helper-text">
      {{ props.helperText }}
    </p>
  </div>
</template>

// packages/angular/src/field/textarea.component.ts
import {
  booleanAttribute,
  ChangeDetectionStrategy,
  Component,
  computed,
  input,
} from "@angular/core";
import type { FieldVariant, Size } from "@crosskit-ui/core";
import { ckAriaAttr, ckDataAttr } from "@crosskit-ui/zag-angular";

let uid = 0;

@Component({
  selector: "ck-textarea",
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: {
    "data-scope": "textarea",
    "data-part": "field",
    "[attr.data-variant]": "variant()",
    "[attr.data-invalid]": "attr(invalid())",
    "[attr.data-full-width]": "attr(fullWidth())",
  },
  template: `
    @if (label()) {
      <label data-part="label" [attr.for]="textareaId()">{{ label() }}</label>
    }
    <!-- Auto-resize is CSS; data-value feeds the invisible replica that sizes
         the grid cell. One DOM write on input, no measurement, no hooks. -->
    <div
      data-scope="textarea"
      data-part="control"
      [attr.data-auto-resize]="attr(autoResize())"
      [attr.data-value]="autoResize() ? value() : null"
    >
      <textarea
        [id]="textareaId()"
        data-scope="textarea"
        data-part="input"
        [attr.data-size]="size()"
        [disabled]="disabled()"
        [attr.aria-invalid]="aria(invalid())"
        [attr.aria-describedby]="describedBy()"
        [value]="value()"
        (input)="onInput($event)"
      ></textarea>
    </div>
    @if (errorMessage()) {
      <p [id]="textareaId() + '-error'" data-part="error-text">{{ errorMessage() }}</p>
    } @else if (helperText()) {
      <p [id]="textareaId() + '-helper'" data-part="helper-text">{{ helperText() }}</p>
    }
  `,
})
export class CkTextarea {
  readonly variant = input<FieldVariant>("default");
  readonly size = input<Size>("md");
  readonly label = input<string>();
  readonly helperText = input<string>();
  readonly errorMessage = input<string>();
  readonly invalid = input(false, { transform: booleanAttribute });
  readonly autoResize = input(false, { transform: booleanAttribute });
  readonly fullWidth = input(true, { transform: booleanAttribute });
  readonly disabled = input(false, { transform: booleanAttribute });
  readonly id = input<string>();
  readonly value = input("");

  private readonly instanceId = `ck-textarea-${++uid}`;
  protected readonly textareaId = computed(() => this.id() ?? this.instanceId);
  protected readonly describedBy = computed(() =>
    this.errorMessage()
      ? `${this.textareaId()}-error`
      : this.helperText()
        ? `${this.textareaId()}-helper`
        : null
  );

  protected readonly attr = ckDataAttr;
  protected readonly aria = ckAriaAttr;

  protected onInput(event: Event) {
    if (!this.autoResize()) return;
    const el = event.target as HTMLTextAreaElement;
    el.parentElement?.setAttribute("data-value", el.value);
  }
}
