// packages/angular/src/feedback/tag.component.ts
import { booleanAttribute, ChangeDetectionStrategy, Component, input, output } from "@angular/core";
import { CkIcon } from "../icon/icon.component";

@Component({
  selector: "ck-tag",
  standalone: true,
  imports: [CkIcon],
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: {
    "data-scope": "tag",
    "data-part": "root",
    "[attr.data-variant]": "variant()",
    "[attr.data-color]": "color()",
  },
  template: `
    <ng-content />
    @if (closable()) {
      <button type="button" data-part="close-trigger" aria-label="Remove" (click)="close.emit()">
        <svg ckIcon name="close" size="sm"></svg>
      </button>
    }
  `,
})
export class CkTag {
  readonly variant = input<"default" | "outline" | "solid">("default");
  readonly color = input<"default" | "primary" | "success" | "warning" | "error" | "info">(
    "default"
  );
  readonly closable = input(false, { transform: booleanAttribute });
  readonly close = output<void>();
}

// packages/vue/src/tag/Tag.vue
<script setup lang="ts">
import Icon from "../icon/Icon.vue";

const props = withDefaults(
  defineProps<{
    variant?: "default" | "outline" | "solid";
    color?: "default" | "primary" | "success" | "warning" | "error" | "info";
    closable?: boolean;
  }>(),
  { variant: "default", color: "default", closable: false }
);

defineEmits<{ close: [] }>();
</script>

<template>
  <span data-scope="tag" data-part="root" :data-variant="props.variant" :data-color="props.color">
    <slot />
    <button
      v-if="props.closable"
      type="button"
      data-part="close-trigger"
      aria-label="Remove"
      @click="$emit('close')"
    >
      <Icon name="close" size="sm" />
    </button>
  </span>
</template>
