// packages/svelte/src/dialog/Modal.svelte
<script lang="ts">
  import type { Snippet } from "svelte";
  import * as dialog from "@zag-js/dialog";
  import { useMachine, normalizeProps, portal } from "@zag-js/svelte";
  import { dataAttr, type ModalSize } from "@crosskit-ui/core";
  import { usePresence, presenceNode } from "./presence.svelte";
  import Button from "../button/Button.svelte";

  interface Props {
    open?: boolean;
    defaultOpen?: boolean;
    onOpenChange?: (details: { open: boolean }) => void;
    size?: ModalSize;
    role?: "dialog" | "alertdialog";
    modal?: boolean;
    closeOnEscape?: boolean;
    closeOnInteractOutside?: boolean;
    showCloseButton?: boolean;
    centered?: boolean;
    scrollable?: boolean;
    id?: string;
    class?: string;
    title?: Snippet | string;
    description?: Snippet | string;
    footer?: Snippet;
    children?: Snippet;
  }

  let {
    // $bindable gives `bind:open` — the direct analogue of Vue's v-model:open
    // and Angular's [(open)].
    open = $bindable(undefined),
    defaultOpen,
    onOpenChange,
    size = "md",
    role,
    modal,
    closeOnEscape,
    closeOnInteractOutside,
    showCloseButton = true,
    centered = true,
    scrollable = true,
    id,
    class: klass,
    title,
    description,
    footer,
    children,
  }: Props = $props();

  const uid = $props.id();

  const service = useMachine(dialog.machine, () => ({
    id: id ?? uid,
    open,
    defaultOpen,
    role,
    modal,
    closeOnEscape,
    closeOnInteractOutside,
    onOpenChange(details: { open: boolean }) {
      open = details.open;
      onOpenChange?.(details);
    },
  }));

  const api = $derived(dialog.connect(service, normalizeProps));
  const presence = usePresence(() => ({ present: api.open }));
</script>

{#if presence.present}
  <div use:portal {...api.getBackdropProps()} data-ck="modal"></div>
  <div use:portal {...api.getPositionerProps()} data-ck="modal" data-centered={dataAttr(centered)}>
    <div
      {...api.getContentProps()}
      data-ck="modal"
      data-size={size}
      data-scrollable={dataAttr(scrollable)}
      class={klass}
      use:presenceNode={presence.setNode}
    >
      {#if title}
        <h2 {...api.getTitleProps()}>
          {#if typeof title === "string"}{title}{:else}{@render title()}{/if}
        </h2>
      {/if}
      {#if description}
        <p {...api.getDescriptionProps()}>
          {#if typeof description === "string"}{description}{:else}{@render description()}{/if}
        </p>
      {/if}
      <div data-scope="dialog" data-part="body" data-ck="modal">{@render children?.()}</div>
      {#if footer}
        <div data-scope="dialog" data-part="footer" data-ck="modal">{@render footer()}</div>
      {/if}
      {#if showCloseButton}
        <Button
          variant="ghost"
          size="sm"
          icon="close"
          data-close-trigger=""
          aria-label="Close"
          onclick={() => api.setOpen(false)}
        />
      {/if}
    </div>
  </div>
{/if}

// packages/react/src/dialog/modal.tsx
"use client";

import { useId, type ReactNode } from "react";
import * as dialog from "@zag-js/dialog";
import { useMachine, normalizeProps, Portal } from "@zag-js/react";
import { dataAttr, type ModalSize } from "@crosskit-ui/core";
import { usePresence } from "../use-presence";
import { Button } from "../button/button";

export interface ModalProps {
  /** Controlled. v0 called this `isOpen`. */
  open?: boolean;
  defaultOpen?: boolean;
  /** v0 had `onClose: () => void`; this reports both directions. */
  onOpenChange?: (details: { open: boolean }) => void;
  size?: ModalSize;
  role?: "dialog" | "alertdialog";
  modal?: boolean;
  /** v0 called this `closeOnEsc`. */
  closeOnEscape?: boolean;
  /** v0 called this `closeOnBackdropClick`. */
  closeOnInteractOutside?: boolean;
  showCloseButton?: boolean;
  centered?: boolean;
  scrollable?: boolean;
  id?: string;
  className?: string;
  title?: ReactNode;
  description?: ReactNode;
  footer?: ReactNode;
  children?: ReactNode;
}

export function Modal({
  size = "md",
  showCloseButton = true,
  centered = true,
  scrollable = true,
  id,
  className,
  title,
  description,
  footer,
  children,
  ...machineProps
}: ModalProps) {
  // Unconditional: `id ?? useId()` would be a conditional hook call.
  const autoId = useId();
  const service = useMachine(dialog.machine, { id: id ?? autoId, ...machineProps });
  const api = dialog.connect(service, normalizeProps);
  const { present, setNode } = usePresence(api.open);

  if (!present) return null;

  return (
    <Portal>
      <div {...api.getBackdropProps()} data-ck="modal" />
      {/* data-* applied directly rather than through mergeProps: we are only
          adding attributes, not merging handlers, and zag's prop types do not
          admit arbitrary data-* keys. */}
      <div {...api.getPositionerProps()} data-ck="modal" data-centered={dataAttr(centered)}>
        <div
          ref={setNode}
          {...api.getContentProps()}
          data-ck="modal"
          data-size={size}
          data-scrollable={dataAttr(scrollable)}
          className={className}
        >
          {title != null && <h2 {...api.getTitleProps()}>{title}</h2>}
          {description != null && <p {...api.getDescriptionProps()}>{description}</p>}
          <div data-scope="dialog" data-part="body" data-ck="modal">
            {children}
          </div>
          {footer != null && (
            <div data-scope="dialog" data-part="footer" data-ck="modal">
              {footer}
            </div>
          )}
          {showCloseButton && (
            <Button
              variant="ghost"
              size="sm"
              icon="close"
              data-close-trigger=""
              aria-label="Close"
              onClick={() => api.setOpen(false)}
            />
          )}
        </div>
      </div>
    </Portal>
  );
}
