// packages/react/src/textarea/textarea.tsx
import {
  useId,
  type ChangeEvent,
  type ReactNode,
  type Ref,
  type TextareaHTMLAttributes,
} from "react";
import { ariaAttr, dataAttr, type FieldVariant, type Size } from "@crosskit-ui/core";

export interface TextareaProps extends Omit<TextareaHTMLAttributes<HTMLTextAreaElement>, "size"> {
  variant?: FieldVariant;
  size?: Size;
  label?: ReactNode;
  helperText?: ReactNode;
  invalid?: boolean;
  errorMessage?: ReactNode;
  autoResize?: boolean;
  fullWidth?: boolean;
  ref?: Ref<HTMLTextAreaElement>;
}

export function Textarea({
  variant = "default",
  size = "md",
  label,
  helperText,
  invalid = false,
  errorMessage,
  autoResize = false,
  fullWidth = true,
  disabled,
  id,
  className,
  onChange,
  defaultValue,
  value,
  ref,
  ...rest
}: TextareaProps) {
  const autoId = useId();
  const textareaId = id ?? autoId;
  const describedBy = errorMessage
    ? `${textareaId}-error`
    : helperText
      ? `${textareaId}-helper`
      : undefined;

  // Auto-resize is CSS (see field.css). All this does is mirror the value onto
  // the wrapper so the invisible replica can size the grid cell — one DOM write,
  // no hooks, no measurement. The `field-sizing: content` path ignores it.
  const mirror = (el: HTMLTextAreaElement) => {
    el.parentElement?.setAttribute("data-value", el.value);
  };

  const handleChange = (event: ChangeEvent<HTMLTextAreaElement>) => {
    if (autoResize) mirror(event.currentTarget);
    onChange?.(event);
  };

  return (
    <div
      data-scope="textarea"
      data-part="field"
      data-variant={variant}
      data-invalid={dataAttr(invalid)}
      data-full-width={dataAttr(fullWidth)}
      className={className}
    >
      {label != null && (
        <label data-part="label" htmlFor={textareaId}>
          {label}
        </label>
      )}
      <div
        data-scope="textarea"
        data-part="control"
        data-auto-resize={dataAttr(autoResize)}
        // Seeds the replica so an initial multi-line value is sized correctly —
        // v0 only ever resized on user input, so this case was always wrong.
        data-value={autoResize ? String(value ?? defaultValue ?? "") : undefined}
      >
        <textarea
          ref={ref}
          id={textareaId}
          data-scope="textarea"
          data-part="input"
          data-size={size}
          disabled={disabled}
          aria-invalid={ariaAttr(invalid)}
          aria-describedby={describedBy}
          value={value}
          defaultValue={defaultValue}
          onChange={handleChange}
          {...rest}
        />
      </div>
      {errorMessage != null ? (
        <p id={`${textareaId}-error`} data-part="error-text">
          {errorMessage}
        </p>
      ) : (
        helperText != null && (
          <p id={`${textareaId}-helper`} data-part="helper-text">
            {helperText}
          </p>
        )
      )}
    </div>
  );
}

// packages/vue/src/textarea/Textarea.vue
<script setup lang="ts">
import { computed, useId } from "vue";
import { ariaAttr, dataAttr, type FieldVariant, type Size } from "@crosskit-ui/core";

const props = withDefaults(
  defineProps<{
    variant?: FieldVariant;
    size?: Size;
    label?: string;
    helperText?: string;
    invalid?: boolean;
    errorMessage?: string;
    autoResize?: boolean;
    fullWidth?: boolean;
    disabled?: boolean;
    id?: string;
    modelValue?: string;
  }>(),
  {
    variant: "default",
    size: "md",
    invalid: false,
    autoResize: false,
    fullWidth: true,
    disabled: false,
  }
);

const emit = defineEmits<{ "update:modelValue": [string] }>();

const autoId = useId();
const textareaId = computed(() => props.id ?? autoId);
const describedBy = computed(() =>
  props.errorMessage
    ? `${textareaId.value}-error`
    : props.helperText
      ? `${textareaId.value}-helper`
      : undefined
);

// Auto-resize is CSS. This only mirrors the value onto the wrapper so the
// invisible replica can size the grid cell — one DOM write, no measurement.
function onInput(event: Event) {
  const el = event.target as HTMLTextAreaElement;
  if (props.autoResize) el.parentElement?.setAttribute("data-value", el.value);
  emit("update:modelValue", el.value);
}
</script>

<template>
  <div
    data-scope="textarea"
    data-part="field"
    :data-variant="props.variant"
    :data-invalid="dataAttr(props.invalid)"
    :data-full-width="dataAttr(props.fullWidth)"
  >
    <label v-if="props.label" data-part="label" :for="textareaId">{{ props.label }}</label>
    <div
      data-scope="textarea"
      data-part="control"
      :data-auto-resize="dataAttr(props.autoResize)"
      :data-value="props.autoResize ? (props.modelValue ?? '') : undefined"
    >
      <textarea
        :id="textareaId"
        data-scope="textarea"
        data-part="input"
        :data-size="props.size"
        :disabled="props.disabled"
        :aria-invalid="ariaAttr(props.invalid)"
        :aria-describedby="describedBy"
        :value="props.modelValue"
        @input="onInput"
      />
    </div>
    <p v-if="props.errorMessage" :id="`${textareaId}-error`" data-part="error-text">
      {{ props.errorMessage }}
    </p>
    <p v-else-if="props.helperText" :id="`${textareaId}-helper`" data-part="helper-text">
      {{ props.helperText }}
    </p>
  </div>
</template>
